version: '3.3'
services:
    dp-import-cantabular-dimension-options:
        build:
            context: ../../../dp-import-cantabular-dimension-options
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -coverpkg=github.com/ONSdigital/dp-import-cantabular-dataset/... 
            - -component
        volumes:
            - ../../:/dp-import-cantabular-dimension-options
        depends_on:
            - kafka
        ports:
            - 26200:26200
        environment:
            BIND_ADDR:          ":26200"
            KAFKA_ADDR:         "kafka:9092"
            DATASET_API_URL:    "http://dp-dataset-api:22000"
            CANTABULAR_URL:     "http://dp-cantabular-server:8491"
            SERVICE_AUTH_TOKEN: "testToken"
