// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/cantabular"
	"github.com/ONSdigital/dp-import-cantabular-dimension-options/handler"
	"sync"
)

// Ensure, that CantabularClientMock does implement handler.CantabularClient.
// If this is not the case, regenerate this file with moq.
var _ handler.CantabularClient = &CantabularClientMock{}

// CantabularClientMock is a mock implementation of handler.CantabularClient.
//
// 	func TestSomethingThatUsesCantabularClient(t *testing.T) {
//
// 		// make and configure a mocked handler.CantabularClient
// 		mockedCantabularClient := &CantabularClientMock{
// 			GetDimensionOptionsFunc: func(ctx context.Context, req cantabular.StaticDatasetQueryRequest) (*cantabular.GetDimensionOptionsResponse, error) {
// 				panic("mock out the GetDimensionOptions method")
// 			},
// 		}
//
// 		// use mockedCantabularClient in code that requires handler.CantabularClient
// 		// and then make assertions.
//
// 	}
type CantabularClientMock struct {
	// GetDimensionOptionsFunc mocks the GetDimensionOptions method.
	GetDimensionOptionsFunc func(ctx context.Context, req cantabular.StaticDatasetQueryRequest) (*cantabular.GetDimensionOptionsResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDimensionOptions holds details about calls to the GetDimensionOptions method.
		GetDimensionOptions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req cantabular.StaticDatasetQueryRequest
		}
	}
	lockGetDimensionOptions sync.RWMutex
}

// GetDimensionOptions calls GetDimensionOptionsFunc.
func (mock *CantabularClientMock) GetDimensionOptions(ctx context.Context, req cantabular.StaticDatasetQueryRequest) (*cantabular.GetDimensionOptionsResponse, error) {
	if mock.GetDimensionOptionsFunc == nil {
		panic("CantabularClientMock.GetDimensionOptionsFunc: method is nil but CantabularClient.GetDimensionOptions was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req cantabular.StaticDatasetQueryRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetDimensionOptions.Lock()
	mock.calls.GetDimensionOptions = append(mock.calls.GetDimensionOptions, callInfo)
	mock.lockGetDimensionOptions.Unlock()
	return mock.GetDimensionOptionsFunc(ctx, req)
}

// GetDimensionOptionsCalls gets all the calls that were made to GetDimensionOptions.
// Check the length with:
//     len(mockedCantabularClient.GetDimensionOptionsCalls())
func (mock *CantabularClientMock) GetDimensionOptionsCalls() []struct {
	Ctx context.Context
	Req cantabular.StaticDatasetQueryRequest
} {
	var calls []struct {
		Ctx context.Context
		Req cantabular.StaticDatasetQueryRequest
	}
	mock.lockGetDimensionOptions.RLock()
	calls = mock.calls.GetDimensionOptions
	mock.lockGetDimensionOptions.RUnlock()
	return calls
}
