---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.4

inputs:
  - name: dp-import-cantabular-dimension-options

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-import-cantabular-dimension-options/ci/scripts/build.sh
